[project]
name = "Hoteler"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Valery Shcherbakov", email = "val0326@mail.ru" }
]
requires-python = ">=3.10"

# Исправленный блок зависимостей
dependencies = [
    "fastapi>=0.112.0",
    "uvicorn[standard]>=0.30.5",
    "pydantic-settings>=2.4.0",
    "pydantic[email]>=2.4.0",
    "sqlalchemy>=2.0.32",
    "alembic>=1.13.3",
    "python-dotenv>=1.0.1",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt==4.0.1",
    "psycopg2-binary>=2.9.9",
    "pyjwt>=2.8.0",
    "python-multipart>=0.0.6",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
